-- MySQL Script generated by MySQL Workbench
-- Tue Nov 23 11:46:15 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Player`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Player` (
  `Login` VARCHAR(255) NOT NULL,
  `Passwoard` VARCHAR(255) NOT NULL,
  `Balance` FLOAT NOT NULL DEFAULT 0,
  `idcard` VARCHAR(45) NOT NULL,
  `Bankcard` VARCHAR(16) NOT NULL,
  PRIMARY KEY (`Login`),
  UNIQUE INDEX `Login_UNIQUE` (`Login` ASC) VISIBLE,
  UNIQUE INDEX `id-card_UNIQUE` (`idcard` ASC) VISIBLE,
  UNIQUE INDEX `Bankcard_UNIQUE` (`Bankcard` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Operation_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Operation_type` (
  `idOperation_type` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idOperation_type`),
  UNIQUE INDEX `idOperation type_UNIQUE` (`idOperation_type` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Operations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Operations` (
  `idOperation` INT NOT NULL AUTO_INCREMENT,
  `Player_login` VARCHAR(45) NOT NULL,
  `Sum1` FLOAT NOT NULL DEFAULT 0,
  `Commission` FLOAT NOT NULL DEFAULT 0,
  `Date1` datetime NOT NULL,
  `Operation_type` INT NOT NULL,
  PRIMARY KEY (`idOperation`),
  UNIQUE INDEX `idOperation_UNIQUE` (`idOperation` ASC) VISIBLE,
  INDEX `Player_idx` (`Player_login` ASC) VISIBLE,
  INDEX `Operation_type_idx` (`Operation_type` ASC) VISIBLE,
  CONSTRAINT `Player`
    FOREIGN KEY (`Player_login`)
    REFERENCES `mydb`.`Player` (`Login`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Operation_type`
    FOREIGN KEY (`Operation_type`)
    REFERENCES `mydb`.`Operation_type` (`idOperation_type`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Location` (
  `idLocation` INT NOT NULL AUTO_INCREMENT,
  `City` VARCHAR(255) NOT NULL,
  `Street` VARCHAR(255) NOT NULL,
  `House_number` VARCHAR(45) NOT NULL,
  `Flat_number` VARCHAR(45) NULL,
  PRIMARY KEY (`idLocation`),
  UNIQUE INDEX `idLocation_UNIQUE` (`idLocation` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Seasons`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Seasons` (
  `idSeasons` INT NOT NULL AUTO_INCREMENT,
  `Name_season` VARCHAR(45) NULL,
  `Prize fund` FLOAT NOT NULL,
  `Number_of_players` INT NOT NULL DEFAULT 0,
  `Number_of_tournaments` INT NOT NULL DEFAULT 0,
  `Start date` DATE NOT NULL,
  `End date` DATE NOT NULL,
  PRIMARY KEY (`idSeasons`),
  UNIQUE INDEX `idSeasons_UNIQUE` (`idSeasons` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tournaments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tournaments` (
  `idTournament` INT NOT NULL AUTO_INCREMENT,
  `Date` DATE NOT NULL,
  `Place` INT NOT NULL,
  `Season` INT NOT NULL,
  `Number_of_players` INT NOT NULL DEFAULT 0,
  `Prize_fund` FLOAT NOT NULL DEFAULT 0,
  `Winner_login` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idTournament`),
  UNIQUE INDEX `id Tournament_UNIQUE` (`idTournament` ASC) VISIBLE,
  INDEX `Season_idx` (`Season` ASC) VISIBLE,
  INDEX `Winner_idx` (`Winner_login` ASC) VISIBLE,
  INDEX `Place_idx` (`Place` ASC) VISIBLE,
  CONSTRAINT `Season`
    FOREIGN KEY (`Season`)
    REFERENCES `mydb`.`Seasons` (`idSeasons`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Winner`
    FOREIGN KEY (`Winner_login`)
    REFERENCES `mydb`.`Player` (`Login`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Place`
    FOREIGN KEY (`Place`)
    REFERENCES `mydb`.`Location` (`idLocation`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tours`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tours` (
  `idTours` INT NOT NULL AUTO_INCREMENT,
  `Tournament` INT NOT NULL,
  `Date` DATE NOT NULL,
  UNIQUE INDEX `idTours_UNIQUE` (`idTours` ASC) VISIBLE,
  PRIMARY KEY (`idTours`),
  INDEX `Tournament_idx` (`Tournament` ASC) VISIBLE,
  CONSTRAINT `Tournament`
    FOREIGN KEY (`Tournament`)
    REFERENCES `mydb`.`Tournaments` (`idTournament`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tables`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tables` (
  `idTables` INT NOT NULL,
  `Tour` INT NOT NULL,
  `Number_of_players` INT NOT NULL DEFAULT 0,
  `Prize_fund` FLOAT NOT NULL DEFAULT 0,
  `Winer_login` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idTables`),
  INDEX `Winner_idx` (`Winer_login` ASC) VISIBLE,
  INDEX `Tourn_idx` (`Tour` ASC) VISIBLE,
  CONSTRAINT `Winner1`
    FOREIGN KEY (`Winer_login`)
    REFERENCES `mydb`.`Player` (`Login`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `Tourn`
    FOREIGN KEY (`Tour`)
    REFERENCES `mydb`.`Tours` (`idTours`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
insert into Player (Login, Passwoard, idcard, bankcard) values  ("Oleh", "123", "123456", "1234123412341234"), ("Olep", "123", "12346", "1234923412341234");
select * from Player;
select SLEEP(2);
insert into Player (Login, Passwoard, idcard, bankcard) values  ("Oled", "123", "123406", "1234123412341230"), ("Olei", "123", "12306", "1234923412341230");
select * from Player;
select SLEEP(2);
delete from Player where Login="Olep";
update Player set Passwoard="123456" where Login = "Oleh";
select Login, Passwoard from Player;
insert into Operation_type (Name) values  ("plus"), ("minus");
select SLEEP(2);
select * from Operation_type;
insert into Operations(Player_login, Sum1, Date1, Operation_type) values ("Oleh", 123, NOW(), 1),("Oleh", 123, NOW(), 2),("Oled", 123, NOW(), 1),("Olei", 123, NOW(), 1);
select SLEEP(2);
select idOperation, Player_login, Sum1 from Operations where Operation_type=1;
drop database mydb;